### ISSUE TITLE
Navegação de Menus 

### ISSUE THREAD

**Issue by Michael-Julio29** [OCAM/BASEDEDADOS#22]
Quando navega-se fora da Raiz, isto e, dentro de uma pasta, ao requisitar uma outra pagina na raiz da erro!!!!
Ex:http://bdocamtestes.itis-server.com/Inscricao/FormListarFormandos.aspx?ic=3213a59d-1bb0-45ca-8ed2-f9a4e3b20372(Estando na pagina FormListarFormandos.aspx dentro da pasta (Inscricao) e ao pesquisar outro menu ele procura na pasta corrente(Inscricao)).

**Comment by comeab** [comment]
Resolvido...incluir / (slash) no inicio de cada uma destas pafinas
