### ISSUE TITLE
[Despacho]: Solciitar os ultimos numeros de membro para cada tipo e colegio - urgente

### ISSUE THREAD

**Issue by comeab** [OCAM/BASEDEDADOS#41]
e importante para alterar o metodo que gera os despachos de forma a somar com numeros mais reais

**Comment by miliate** [comment]
1-Contabilistas
 Individuais: 2984/cc/ocam/2015
Sociedades: 66/scc/ocam2014
2-Auditores 
Individuais: 85/CA/ocam/2015
Sociedades: 11/sca/ocam2014
