### ISSUE TITLE
Inscricao de Membro

### ISSUE THREAD

**Issue by miliate** [OCAM/BASEDEDADOS#5]
-Gerar as tabelas e testar o formulário de inscrição
-Fazer o formulario de candidaturas submetidas com a possibiliade de vizualizar os anexos e confirmar  ou aprovar a candidatura

**Comment by comeab** [comment]
USE [OrdensDB]
GO

/*****\* Object:  Table [dbo].[CandidatoMembro]    Script Date: 03/19/2015 12:33:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CandidatoMembro]([id] [int] IDENTITY%281,1%29 NOT NULL,
    [nome] [varchar]%28max%29 NULL,
    [datanasc] [date] NULL,
    [sexo] [varchar]%2850%29 NULL,
    [provincia_id] [int] NULL,
    [pais_Origem_id] [int] NULL,
    [tipoDoc] [int] NULL,
    [nrDoc] [varchar]%2850%29 NULL,
    [tel1] [varchar]%2850%29 NULL,
    [tel2] [varchar]%2850%29 NULL,
    [email1] [varchar]%2850%29 NULL,
    [email2] [varchar]%2850%29 NULL,
    [endereco] [varchar]%28max%29 NULL,
    [nuit] [varchar]%2850%29 NULL,
    [processocriminal] [bit] NULL,
    [EstadoCivi_id] [int] NULL,
    [Usuario_id] [int] NULL,
    [nrMembro] [varchar]%2850%29 NULL,
    [nrCedula] [varchar]%2850%29 NULL,
    [data_validade_doc] [date] NULL,
    [data_despacho] [date] NULL,
    [data_registo] [datetime] NULL,
    [data_entrada] [date] NULL,
    [idCandidatoTipo] [int] NULL,
    [status_processo] [int] NULL,
    [idColegioTipoStatus] [int] NULL,
    [idMembroTipoStatus] [int] NULL,
 CONSTRAINT [PK_CandidatoMembro] PRIMARY KEY CLUSTERED 
%28
    [id] ASC
%29WITH %28PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON%29 ON [PRIMARY]) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CandidatoMembro]  WITH CHECK ADD  CONSTRAINT [FK_CandidatoMembro_ColegioTipoStatus] FOREIGN KEY([idColegioTipoStatus])
REFERENCES [dbo].[ColegioTipoStatus]([id])
GO

ALTER TABLE [dbo].[CandidatoMembro] CHECK CONSTRAINT [FK_CandidatoMembro_ColegioTipoStatus]
GO

ALTER TABLE [dbo].[CandidatoMembro]  WITH CHECK ADD  CONSTRAINT [FK_CandidatoMembro_MembroStatus] FOREIGN KEY([idMembroTipoStatus])
REFERENCES [dbo].[MembroStatus]([id])
GO

ALTER TABLE [dbo].[CandidatoMembro] CHECK CONSTRAINT [FK_CandidatoMembro_MembroStatus]
GO

USE [OrdensDB]
GO

/*****\* Object:  Table [dbo].[Anexo]    Script Date: 03/19/2015 12:33:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Anexo]([id] [int] IDENTITY%281,1%29 NOT NULL,
    [nome] [varchar]%28max%29 NULL,
 CONSTRAINT [PK_Anexo] PRIMARY KEY CLUSTERED 
%28
    [id] ASC
%29WITH %28PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON%29 ON [PRIMARY]) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
