### ISSUE TITLE
[Empresas] - Rebind da RadList no fim de Cadastro de Empresa

### ISSUE THREAD

**Issue by Michael-Julio29** [OCAM/BASEDEDADOS#60]
*Motivo
- No fim de cadastro de nova empresa, os usuários tentam pesquisar sem antes  fazer um refresh, e tentam cadastrar de novo porque nao encontram. O que nos salva eh a validacao dos campos (NUIT)

**Comment by comeab** [comment]
Falta apenas ajaxficiar
